services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
        networks:
            - sail
            - web
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        restart: 'unless-stopped'
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 5s
            retries: 10
networks:
    sail:
        driver: bridge
    web:
        external: true
volumes:
    sail-mysql:
        driver: local
